package com.prototype.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.prototype.entity.Msuser;

@Mapper
public interface MsuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int insert(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int insertSelective(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    Msuser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int updateByPrimaryKeySelective(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int updateByPrimaryKey(Msuser record);
}