package com.prototype.mapper;

import java.util.List;

import com.prototype.entity.Msuser;

public interface MsuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int insert(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int insertSelective(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    Msuser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int updateByPrimaryKeySelective(Msuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSUSER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int updateByPrimaryKey(Msuser record);

    List<Msuser> selectAll();
}