package com.prototype.mapper;

import com.prototype.entity.Trworktime;
import org.apache.ibatis.annotations.Param;

public interface TrworktimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int deleteByPrimaryKey(@Param("day") String day, @Param("month") String month, @Param("userid") String userid, @Param("year") String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int insert(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int insertSelective(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    Trworktime selectByPrimaryKey(@Param("day") String day, @Param("month") String month, @Param("userid") String userid, @Param("year") String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int updateByPrimaryKeySelective(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    int updateByPrimaryKey(Trworktime record);
}