package com.prototype.mapper;

import com.prototype.entity.Trworktime;
import org.apache.ibatis.annotations.Param;

public interface TrworktimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int deleteByPrimaryKey(@Param("userid") String userid, @Param("year") String year, @Param("month") String month, @Param("day") String day);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int insert(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int insertSelective(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    Trworktime selectByPrimaryKey(@Param("userid") String userid, @Param("year") String year, @Param("month") String month, @Param("day") String day);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int updateByPrimaryKeySelective(Trworktime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRWORKTIME
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    int updateByPrimaryKey(Trworktime record);
}