package com.prototype.entity;

import java.util.Date;

public class Msuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.userid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.username
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.userpswd
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String userpswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.userclass
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String userclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.insertuserid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String insertuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.insertusername
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String insertusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.insertdate
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private Date insertdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.rev
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private Integer rev;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.userid
     *
     * @return the value of MSUSER.userid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.userid
     *
     * @param userid the value for MSUSER.userid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.username
     *
     * @return the value of MSUSER.username
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.username
     *
     * @param username the value for MSUSER.username
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.userpswd
     *
     * @return the value of MSUSER.userpswd
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.userpswd
     *
     * @param userpswd the value for MSUSER.userpswd
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.userclass
     *
     * @return the value of MSUSER.userclass
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getUserclass() {
        return userclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.userclass
     *
     * @param userclass the value for MSUSER.userclass
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setUserclass(String userclass) {
        this.userclass = userclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.insertuserid
     *
     * @return the value of MSUSER.insertuserid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getInsertuserid() {
        return insertuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.insertuserid
     *
     * @param insertuserid the value for MSUSER.insertuserid
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setInsertuserid(String insertuserid) {
        this.insertuserid = insertuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.insertusername
     *
     * @return the value of MSUSER.insertusername
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getInsertusername() {
        return insertusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.insertusername
     *
     * @param insertusername the value for MSUSER.insertusername
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setInsertusername(String insertusername) {
        this.insertusername = insertusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.insertdate
     *
     * @return the value of MSUSER.insertdate
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public Date getInsertdate() {
        return insertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.insertdate
     *
     * @param insertdate the value for MSUSER.insertdate
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setInsertdate(Date insertdate) {
        this.insertdate = insertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.rev
     *
     * @return the value of MSUSER.rev
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.rev
     *
     * @param rev the value for MSUSER.rev
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }
}