package com.prototype.entity;

public class Msuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.userid
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.username
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.userpswd
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    private String userpswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSUSER.rev
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    private Integer rev;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.userid
     *
     * @return the value of MSUSER.userid
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.userid
     *
     * @param userid the value for MSUSER.userid
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.username
     *
     * @return the value of MSUSER.username
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.username
     *
     * @param username the value for MSUSER.username
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.userpswd
     *
     * @return the value of MSUSER.userpswd
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.userpswd
     *
     * @param userpswd the value for MSUSER.userpswd
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSUSER.rev
     *
     * @return the value of MSUSER.rev
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSUSER.rev
     *
     * @param rev the value for MSUSER.rev
     *
     * @mbg.generated Wed Feb 27 22:46:09 JST 2019
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }
}