package com.prototype.entity;

public class Trworktime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.DAY
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.MONTH
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.USERID
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.YEAR
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.DAY_OF_WEEK
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String dayOfWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.DAY_KIND
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String dayKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.WKTM_FROM_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String wktmFromH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.WKTM_FROM_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String wktmFromM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.WKTM_TO_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String wktmToH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.WKTM_TO_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String wktmToM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRWORKTIME.OTHER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.DAY
     *
     * @return the value of TRWORKTIME.DAY
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.DAY
     *
     * @param day the value for TRWORKTIME.DAY
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.MONTH
     *
     * @return the value of TRWORKTIME.MONTH
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.MONTH
     *
     * @param month the value for TRWORKTIME.MONTH
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.USERID
     *
     * @return the value of TRWORKTIME.USERID
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.USERID
     *
     * @param userid the value for TRWORKTIME.USERID
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.YEAR
     *
     * @return the value of TRWORKTIME.YEAR
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.YEAR
     *
     * @param year the value for TRWORKTIME.YEAR
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.DAY_OF_WEEK
     *
     * @return the value of TRWORKTIME.DAY_OF_WEEK
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.DAY_OF_WEEK
     *
     * @param dayOfWeek the value for TRWORKTIME.DAY_OF_WEEK
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.DAY_KIND
     *
     * @return the value of TRWORKTIME.DAY_KIND
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getDayKind() {
        return dayKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.DAY_KIND
     *
     * @param dayKind the value for TRWORKTIME.DAY_KIND
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setDayKind(String dayKind) {
        this.dayKind = dayKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.WKTM_FROM_H
     *
     * @return the value of TRWORKTIME.WKTM_FROM_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getWktmFromH() {
        return wktmFromH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.WKTM_FROM_H
     *
     * @param wktmFromH the value for TRWORKTIME.WKTM_FROM_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setWktmFromH(String wktmFromH) {
        this.wktmFromH = wktmFromH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.WKTM_FROM_M
     *
     * @return the value of TRWORKTIME.WKTM_FROM_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getWktmFromM() {
        return wktmFromM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.WKTM_FROM_M
     *
     * @param wktmFromM the value for TRWORKTIME.WKTM_FROM_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setWktmFromM(String wktmFromM) {
        this.wktmFromM = wktmFromM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.WKTM_TO_H
     *
     * @return the value of TRWORKTIME.WKTM_TO_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getWktmToH() {
        return wktmToH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.WKTM_TO_H
     *
     * @param wktmToH the value for TRWORKTIME.WKTM_TO_H
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setWktmToH(String wktmToH) {
        this.wktmToH = wktmToH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.WKTM_TO_M
     *
     * @return the value of TRWORKTIME.WKTM_TO_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getWktmToM() {
        return wktmToM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.WKTM_TO_M
     *
     * @param wktmToM the value for TRWORKTIME.WKTM_TO_M
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setWktmToM(String wktmToM) {
        this.wktmToM = wktmToM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRWORKTIME.OTHER
     *
     * @return the value of TRWORKTIME.OTHER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRWORKTIME.OTHER
     *
     * @param other the value for TRWORKTIME.OTHER
     *
     * @mbggenerated Fri Mar 15 23:56:18 JST 2019
     */
    public void setOther(String other) {
        this.other = other;
    }
}